### ISSUE TITLE
Make sure pathogens are detected for mapdamage to run

### ISSUE THREAD

**Issue by percyfal** [NBISweden/ancient-microbiome-smk#1]
Currently no pathogens are detected, which has to do with test data setup. Make sure there is output data for mapdamage to work on. One could possibly also rewrite the rule such that mapdamage will write empty output files and warn that no pathogens were found.

**Comment by LeandroRitter** [comment]
maoDamage seems to work fine when the pathogensFound.tab file is made tab-delimited. The issue seems to have been not due to absence of pathogens (there is in fact Y.pestis) but the pathogensFound.tab file that could not be properly read (because of spaces in the file) and intersected with the filtered output from KrakenUniq

**Comment by percyfal** [comment]
Fixed by #8.
